client_config_backend: settings
client_config:
  client_id: 732616506495-mgq243hgj0gj55ejgcd0iqmcaushohbc.apps.googleusercontent.com
  client_secret: rWLRtcthL5_397zQoKhlWMWC

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install